country_continent_mapping = {
    'United States': 'North America',
    'Canada': 'North America',
    'Mexico': 'North America',
    'Bermuda': 'North America',
    'Puerto Rico': 'North America',
    'Cayman Islands': 'North America',
    'Guatemala': 'North America',
    
    'Brazil': 'South America',
    'Chile': 'South America',
    'Colombia': 'South America',
    'Argentina': 'South America',
    'Peru': 'South America',
    
    'France': 'Europe',
    'United Kingdom': 'Europe',
    'Sweden': 'Europe',
    'Ireland': 'Europe',
    'Switzerland': 'Europe',
    'Portugal': 'Europe',
    'Netherlands': 'Europe',
    'Denmark': 'Europe',
    'Germany': 'Europe',
    'Belgium': 'Europe',
    'Norway': 'Europe',
    'Romania': 'Europe',
    'Austria': 'Europe',
    'Spain': 'Europe',
    'Greece': 'Europe',
    'Italy': 'Europe',
    'Finland': 'Europe',
    'Estonia': 'Europe',
    'Bulgaria': 'Europe',
    'Cyprus': 'Europe',
    'Croatia': 'Europe',
    'Luxembourg': 'Europe',
    'Czechia': 'Europe',
    'Poland': 'Europe',
    'Lithuania': 'Europe',
    'Slovenia': 'Europe',
    'Latvia': 'Europe',
    'Gibraltar': 'Europe',
    'Ukraine': 'Europe',
    
    'Israel': 'Asia',
    'Turkey': 'Asia',  # unify Türkiye and Turkey
    'Türkiye': 'Asia',
    'Malaysia': 'Asia',
    'Singapore': 'Asia',
    'India': 'Asia',
    'China': 'Asia',
    'Philippines': 'Asia',
    'Saudi Arabia': 'Asia',
    'South Korea': 'Asia',
    'Hong Kong': 'Asia',
    'United Arab Emirates': 'Asia',
    'Japan': 'Asia',
    'Vietnam': 'Asia',
    'Indonesia': 'Asia',
    'Pakistan': 'Asia',
    'Taiwan': 'Asia',
    'Armenia': 'Asia',
    'Russia': 'Asia',
    
    'Egypt': 'Africa',
    'South Africa': 'Africa',
    'Nigeria': 'Africa',
    'Morocco': 'Africa',
    'Ghana': 'Africa',
    
    'Australia': 'Oceania',
    'New Zealand': 'Oceania',
    
    # Handle missing
    None: 'Unknown',
    '<NA>': 'Unknown'
}
