import pandas as pd

typo_corrections = {
    'PRE__SEED': 'PRE_SEED',
    'SERIES_A1': 'SERIES_A',
    'SERIES_A2': 'SERIES_A',
    'SERIES_A3': 'SERIES_A',
    'SERIES_AA': 'SERIES_A',
    'SERIES_A_EXTENSION': 'SERIES_A',
    'EARLY_STAGE_SERIES_A': 'SERIES_A',
    'SERIES_B1': 'SERIES_B',
    'SERIES_B2': 'SERIES_B',
    'SERIES_B3': 'SERIES_B',
    'SERIES_BB': 'SERIES_B',
    'SERIES_B_EXTENSION': 'SERIES_B',
    'SERIES_C1': 'SERIES_C',
    'SERIES_C2': 'SERIES_C',
    'SERIES_C_EXTENSION': 'SERIES_C',
}

funding_type_buckets = {
    # Seed and Early
    'PRE_SEED': 'SEED/EARLY',
    'SEED': 'SEED/EARLY',
    'SEED_ROUND': 'SEED/EARLY',
    'SEED_EXTENSION': 'SEED/EARLY',
    'ANGEL': 'SEED/EARLY',
    'ANGEL_INDIVIDUAL': 'SEED/EARLY',
    'ACCELERATOR_INCUBATOR': 'SEED/EARLY',
    
    # Venture Stages
    'SERIES_1': 'SERIES_A',
    'SERIES_A': 'SERIES_A',
    'SERIES_B': 'SERIES_B',
    'SERIES_C': 'SERIES_C',
    'SERIES_D': 'SERIES_D_OR_LATER',
    'SERIES_E': 'SERIES_D_OR_LATER',
    'SERIES_F': 'SERIES_D_OR_LATER',
    'SERIES_G': 'SERIES_D_OR_LATER',
    
    # Late VC / PE
    'LATER_STAGE_VC': 'LATE_STAGE',
    'LATER_STAGE_SERIES_B': 'LATE_STAGE',
    'PE_GROWTH': 'LATE_STAGE',
    'PRIVATE_EQUITY': 'LATE_STAGE',
    'BUYOUT_LBO': 'LATE_STAGE',
    'SECONDARY_PRIVATE': 'LATE_STAGE',
    'SECONDARY_TRANSACTION': 'LATE_STAGE',
    'DIV_RECAP': 'LATE_STAGE',
    'LEV_RECAP': 'LATE_STAGE',
    'PIPE': 'LATE_STAGE',
    'M_AND_A': 'LATE_STAGE',
    'POST_IPO_EQUITY': 'LATE_STAGE',
    'POST_IPO_DEBT': 'LATE_STAGE',
    'CAPITALIZATION': 'LATE_STAGE',
    'REVERSE_MERGER': 'LATE_STAGE',
    'BRIDGE': 'LATE_STAGE',
    
    # Alternative / Other
    'GRANT': 'ALTERNATIVE',
    'CROWDFUNDING': 'ALTERNATIVE',
    'EQUITY_CROWDFUNDING': 'ALTERNATIVE',
    'PRODUCT_CROWDFUNDING': 'ALTERNATIVE',
    'PLATFORM': 'ALTERNATIVE',
    'STRATEGIC': 'ALTERNATIVE',
    'NON_EQUITY_ASSISTANCE': 'ALTERNATIVE',
    'JOINT_VENTURE': 'ALTERNATIVE',
    
    # Unknowns
    'SERIES_UNKNOWN': 'UNKNOWN',
    'UNKNOWN': 'UNKNOWN',
    None: 'UNKNOWN',
    pd.NA: 'UNKNOWN'
}

funding_stage_mapping = {
    'PRE_SEED': 'SEED/EARLY',
    'SEED': 'SEED/EARLY',
    'SERIES_A': 'SERIES_A',
    'SERIES_B': 'SERIES_B',
    'SERIES_C': 'SERIES_C',
    'SERIES_D': 'SERIES_D_OR_LATER',
    'SERIES_E': 'SERIES_D_OR_LATER',
    'SERIES_F': 'SERIES_D_OR_LATER',
    'SERIES_G': 'SERIES_D_OR_LATER',
    'SERIES_H': 'SERIES_D_OR_LATER',
    'EXITED': 'OTHER',
    'STEALTH': 'OTHER',
    'VENTURE_UNKNOWN': 'UNKNOWN'
}